background = 0xff{{base00_hex}}
base = 0xff{{black2_hex}}
alternate_base = 0xff{{one_bg_hex}}
text = 0xff{{base06_hex}}
bright_text = 0xff{{base07_hex}}
link_text = 0xff{{base0C_hex}}
accent = 0xff{{base0D_hex}}
accent_secondary = 0xff{{base0E_hex}}

font_family = JetBrainsMono Nerd Font
font_size = 12
small_font_size = 11
