$bg = rgb({{base00_hex}})
$bg_translucent = rgba({{base00_hex}}d9)
$fg = rgb({{base07_hex}})
$dim = rgb({{base04_hex}})
$light_grey = rgb({{light_grey_hex}})
$red = rgb({{base08_hex}})
$green = rgb({{base0B_hex}})
$yellow = rgb({{base0A_hex}})
$blue = rgb({{base0D_hex}})
$magenta = rgb({{base0E_hex}})
$cyan = rgb({{base0C_hex}})
