#!/usr/bin/python

import re
from subprocess import check_output

from colors import colors
from jira import get_jira_issue, get_jira_link


def get_commit():
    return check_output(["git", "log", "-1", "HEAD", "--pretty=oneline", "--abbrev-commit"]).decode("utf-8")


def get_commit_message():
    p = re.compile('^\S+ (?P<message>.+)')
    commit = get_commit()
    m = p.search(commit)
    if m is None:
        return None
    m.group('message')
    message = m.group(1)
    if message is None:
        return None
    return message


if __name__ == '__main__':
    try:
        msg = get_commit_message()
        issue = get_jira_issue(msg)
        if issue is not None:
            print('Remember to {OKBL}log you hours{ENDC}: {UNDERLINE}{}{ENDC}'.format(
                get_jira_link(issue), **colors
            ))
    except Exception as e:
        pass
    exit(0)
