# Default colors
[colors.primary]
background = '#{{base00_hex}}'
foreground = '#{{base05_hex}}'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#{{base00_hex}}'
cursor = '#{{base05_hex}}'

# Normal colors
[colors.normal]
black = '#{{base00_hex}}'
red = '#{{base08_hex}}'
green = '#{{base0B_hex}}'
yellow = '#{{base0A_hex}}'
blue = '#{{base0D_hex}}'
magenta = '#{{base0E_hex}}'
cyan = '#{{base0C_hex}}'
white = '#{{base05_hex}}'

# Bright colors
[colors.bright]
black = '#{{base03_hex}}'
red = '#{{base08_hex}}'
green = '#{{base0B_hex}}'
yellow = '#{{base0A_hex}}'
blue = '#{{base0D_hex}}'
magenta = '#{{base0E_hex}}'
cyan = '#{{base0C_hex}}'
white = '#{{base07_hex}}'

[[colors.indexed_colors]]
index = 16
color = "#{{base09_hex}}"

[[colors.indexed_colors]]
index = 17
color = "#{{base0F_hex}}"

[[colors.indexed_colors]]
index = 18
color = "#{{base01_hex}}"

[[colors.indexed_colors]]
index = 19
color = "#{{base02_hex}}"

[[colors.indexed_colors]]
index = 20
color = "#{{base04_hex}}"

[[colors.indexed_colors]]
index = 21
color = "#{{base06_hex}}"
