---
- hosts: "{{ host }}"

  vars:
    # renovate: datasource=github-releases depName=natscli packageName=nats-io/natscli
    version: v0.4.0
    # renovate: datasource=github-releases depName=nsc packageName=nats-io/nsc
    nsc_version: v2.12.2
    # renovate: datasource=github-releases depName=nkeys packageName=nats-io/nkeys
    nk_version: v0.4.15

  tasks:
    - name: Create local bin path
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory

    - name: Check if nats is installed
      shell: "nats --version | grep {{ version[1:] }}"
      changed_when: false
      failed_when: nats_installed.rc not in [0,1]
      register: nats_installed

    - name: Install nats
      when: nats_installed.rc not in [ 0 ]
      unarchive:
        remote_src: yes
        src: "https://github.com/nats-io/natscli/releases/download/{{ version }}/nats-{{ version[1:] }}-linux-amd64.zip"
        dest: ~/.local/bin

    - name: Link nats
      when: nats_installed.rc not in [ 0 ]
      ansible.builtin.file:
        src: "~/.local/bin/nats-{{ version[1:] }}-linux-amd64/nats"
        dest: ~/.local/bin/nats
        state: link

    - name: Check if nsc is installed
      shell: "nsc --version | grep {{ nsc_version[1:] }}"
      changed_when: false
      failed_when: nsc_installed.rc not in [0,1]
      register: nsc_installed

    - name: Install nsc
      when: nsc_installed.rc not in [ 0 ]
      unarchive:
        remote_src: yes
        src: "https://github.com/nats-io/nsc/releases/download/{{ nsc_version }}/nsc-linux-amd64.zip"
        dest: ~/.local/bin

    - name: Check if nk is installed
      shell: "nk --version | grep {{ nk_version[1:] }}"
      changed_when: false
      failed_when: nk_installed.rc not in [0,1]
      register: nk_installed

    - name: Install nk
      when: nk_installed.rc not in [ 0 ]
      unarchive:
        remote_src: yes
        src: "https://github.com/nats-io/nkeys/releases/download/{{ nk_version }}/nkeys-{{ nk_version }}-linux-amd64.zip"
        dest: ~/.local/bin

    - name: Link nk
      when: nk_installed.rc not in [ 0 ]
      ansible.builtin.file:
        src: "~/.local/bin/nkeys-{{ nk_version }}-linux-amd64/nk"
        dest: ~/.local/bin/nk
        state: link
