# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
disableStartupPopups: true
git:
  autoFetch: false
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  showCommandLog: false
  showBottomLine: false
  showPanelJumps: false
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - "#353b45"
customCommands:
  - key: "G"
    description: "Cleanup local branches"
    context: "localBranches"
    command: "git gone"
    output: popup
  - key: "n"
    description: "New branch"
    context: "localBranches"
    prompts:
      - type: "input"
        title: "New branch name (branch is off of '{{.SelectedLocalBranch.Name}}')"
        key: "BranchName"
        initialValue: "gbbirkisson/"
    command: "git checkout -b {{.Form.BranchName}} refs/heads/{{.SelectedLocalBranch.Name}}"
  - key: 'o'
    description: "New PR"
    context: 'localBranches'
    prompts:
      - type: "input"
        title: "New PR: Title?"
        key: "PRTitle"
        initialValue: "{{ .SelectedCommit.Name }}"
      - type: "menu"
        title: "New PR: Draft?"
        key: "PRDraft"
        options:
          - name: "yes"
            value: "yes"
          - name: "no"
            value: "no"
      - type: "confirm"
        title: "New PR: Create?"
        body: "Create a {{if eq .Form.PRDraft \"yes\"}}draft {{end}}PR '{{.Form.PRTitle}}' into 'main' from '{{.SelectedLocalBranch.Name}}'"
    command: |
      set -e

      gh pr create {{if eq .Form.PRDraft "yes"}}-d{{end}} \
        -H {{.SelectedLocalBranch.Name}} \
        -a @me \
        -t {{.Form.PRTitle|quote}} \
        -b ''

      gh pr view -w $(gh pr list -H {{.SelectedLocalBranch.Name}} --json number --jq .[0].number) &>/dev/null &
    output: terminal
  - key: 'O'
    context: 'localBranches'
    command: |
      gh pr view -w $(gh pr list -H {{.SelectedLocalBranch.Name}} --json number --jq .[0].number) &>/dev/null &
