---
- hosts: localhost

  tasks:
    - name: Install packages
      become: true
      apt:
        state: latest
        update_cache: true
        pkg:
          # Bare essentials
          - build-essential
          - cmake
          - direnv

          # Python dependencies
          - libbz2-dev
          - libffi-dev
          - liblzma-dev
          - libncurses-dev
          - libreadline6-dev
          - libsqlite3-dev
          - libssl-dev
          - tk-dev

          # Other
          - jq            # Json manipulation
          - tree          # Tree for directories
          - wireguard     # VPN
          - timg          # Cat images in terminal

          # Dicts
          - dictd
          - dict-devil   # "The Devil's Dictionary" by Ambrose Bierce
          - dict-foldoc  # FOLDOC dictionary database
          - dict-gcide   # Comprehensive English Dictionary
          - dict-jargon  # dict package for The Jargon Lexicon
          - dict-vera    # Dictionary of computer related acronyms -- dict format
          - dict-wn      # electronic lexical database of English language for dict

          # X11
          # - gnome-tweaks  # Tweak gnome
          # - tmux          # Terminal good stuff
          # - xclip         # For nvim clipboard
