---
- hosts: localhost

  tasks:
    - name: Link
      command: "./link"
      changed_when: false
      args:
        chdir: "{{ dotfiles }}"

    - name: Source files
      lineinfile:
        create: true
        path: "{{ item.path }}"
        line: "{{ item.line }}"
      with_items:
        - path: ~/.profile
          line: "source $HOME/.profile_gbb"
