background = 0xff1e222a
base = 0xff252931
alternate_base = 0xff282c34
text = 0xffb6bdca
bright_text = 0xffc8ccd4
link_text = 0xff56b6c2
accent = 0xff61afef
accent_secondary = 0xffc678dd

font_family = JetBrainsMono Nerd Font
font_size = 12
small_font_size = 11
