source = ~/.config/hypr/hyprlock-colors.conf

$font = JetBrainsMono Nerd Font

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 6
    brightness = 0.5
    vibrancy = 0
}

input-field {
    monitor =
    size = 40%, 5%
    outline_thickness = 2
    inner_color = $bg_translucent

    outer_color = $blue
    check_color = $yellow
    fail_color = $red

    font_color = $dim
    fade_on_empty = false
    rounding = 0

    font_family = $font
    placeholder_text =
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    color = $blue
    font_size = 90
    font_family = $font ExtraBold

    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    color = $fg
    font_size = 25
    font_family = $font

    position = -30, -150
    halign = right
    valign = top
}

label {
    monitor =
    text = $LAYOUT[en,is,no]
    color = $light_grey
    font_size = 24
    font_family = $font
    onclick = hyprctl switchxkblayout all next

    position = 18%, -20
    halign = center
    valign = center
}
