$bg = rgb(1e222a)
$bg_translucent = rgba(1e222ad9)
$fg = rgb(c8ccd4)
$dim = rgb(565c64)
$light_grey = rgb(6f737b)
$red = rgb(e06c75)
$green = rgb(98c379)
$yellow = rgb(e5c07b)
$blue = rgb(61afef)
$magenta = rgb(c678dd)
$cyan = rgb(56b6c2)
