---
prSections:
  - title: Mine
    filters: is:open author:@me -label:release -repo:slok/sloth
    layout:
      author:
        hidden: true

  - title: Review (work)
    filters: is:open review-requested:@me -label:release user:amedia -is:draft

  - title: Releases (work)
    filters: is:open user:amedia label:release
    layout:
      author:
        hidden: true

  - title: Review (personal)
    filters: is:open review-requested:@me -label:release -user:amedia

  - title: Releases (personal)
    filters: is:open user:@me label:release
    layout:
      author:
        hidden: true

issuesSections:
  - title: Assigned
    filters: is:open assignee:@me
  - title: Mentions
    filters: is:open mentions:@me -user:enonic
  - title: Created
    filters: is:open author:@me -user:enonic -repo:karloygard/xcomfortd-go

defaults:
  layout:
    prs:
      repo:
        grow: true
        width: 10
        hidden: false
        # issues: same structure as prs
  prsLimit: 20  # global limit
  issuesLimit: 20  # global limit
  preview:
    open: true  # whether to have the preview pane open by default
    width: 70  # width in columns
  refetchIntervalMinutes: 30  # will refetch all sections every 30 minutes

repoPaths:  # configure where to locate repos when checking out PRs
  gbbirkisson/*: ~/repos/personal/*
  :owner/:repo: ~/repos/:owner/:repo

pager:
  diff: less  # or delta for example

confirmQuit: false  # show prompt on quit or not

keybindings:
  issues:
    - key: o
      command: >
        gh issue --repo {{.RepoName}} view {{.IssueNumber}} -w &>/dev/null &
  prs:
    - key: o
      command: >
        gh pr --repo {{.RepoName}} view {{.PrNumber}} -w &>/dev/null &
    - key: C
      command: >
        tmux new-window -c {{.RepoPath}} '
          gh pr checkout {{.PrNumber}} &&
          nvim -c ":DiffviewOpen {{.BaseRefName}}...{{.HeadRefName}}"'
