---
prSections:
  - title: Needs My Review
    filters: is:open review-requested:@me -user:kolonialno
    # limit: 50  # optional limit of rows fetched for this section
  - title: My Pull Requests
    filters: is:open author:@me -user:kolonialno -repo:slok/sloth -label:release
    layout:
      author:
        hidden: true
        # width: <number of columns>
        # grow: <bool> this will make the column grow in size
issuesSections:
  - title: Assigned
    filters: is:open assignee:@me
  - title: Subscribed
    filters: is:open -author:@me repo:gbbirkisson/spis
  - title: Created
    filters: is:open author:@me -user:enonic -user:kolonialno -repo:karloygard/xcomfortd-go -repo:slok/sloth -repo:jgensler8/terraform-provider-minikube
defaults:
  layout:
    prs:
      repo:
        grow: true
        width: 10
        hidden: false
        # issues: same structure as prs
  prsLimit: 20  # global limit
  issuesLimit: 20  # global limit
  preview:
    open: true  # whether to have the preview pane open by default
    width: 60  # width in columns
  refetchIntervalMinutes: 30  # will refetch all sections every 30 minutes
repoPaths:  # configure where to locate repos when checking out PRs
  gbbirkisson/*: ~/repos/personal/*
  :owner/:repo: ~/repos/:owner/:repo
pager:
  diff: less  # or delta for example
confirmQuit: false  # show prompt on quit or not
