#!/usr/bin/env python

# For use in vim with !align to align tables and comments, i.e:
#
# hello // | adfasdf | asdfasfdff |
# howsahoing // | fff | ggg |
# goo
#
# ... becomes ...
#
# hello      // | adfasdf | asdfasfdff |
# howsahoing // | fff     | ggg        |
# goo

import re
import sys

delimiters = [
    "//",
    "#",
    "|",
    '"',
]


def process(lines: list[str], sym: str, start: int) -> list[str]:
    biggest = -1
    for line in lines:
        t = line.find(sym, start)
        if t > biggest:
            biggest = t

    if biggest == -1:
        return lines

    res = []
    for line in lines:
        t = line.find(sym, start)
        if t > -1 and t < biggest:
            res.append(line[:t] + (" " * (biggest - t)) + line[t:])
        else:
            res.append(line)

    return process(res, sym, biggest + 1)


def trim(lines: list[str]) -> list[str]:
    spaces = []
    for line in lines:
        spaces.append([m.end() for m in re.finditer(r"^\s*\S.*\s\s\S", line)])

    common = list(set.intersection(*map(set, spaces)))
    if len(common) == 0:
        return lines

    target = common[0]

    res = []
    for line in lines:
        res.append(line[: target - 2] + line[target - 1 :])

    for line in res:
        if re.findall(r"\S\s#", line):
            return lines

    return res


lines = [line.replace("\t", " ") for line in sys.stdin]
while True:
    new_lines = lines
    for sym in delimiters:
        new_lines = trim(process(new_lines, sym, 0))
    if new_lines != lines:
        lines = new_lines
    else:
        break

for line in lines:
    print(line, end="")
