#!/usr/bin/env bash

set -euo pipefail

ARGS="$@"

SCRIPT=$(
	cat <<EOF
set -euo pipefail

if $ARGS; then
  tput bold
  tput setaf 2
  echo -e '\n✅ SUCCESS ✅'
  tput sgr0
else
  tput bold
  tput setaf 1
  echo -e '\n💩 ERROR 💩'
  tput sgr0
fi
EOF
)

watchexec --quiet --restart --clear --stop-timeout=0 --ignore=.null-ls* --shell=bash -- "$SCRIPT"
