#!/usr/bin/env bash

set -euo pipefail

SCRIPT=$(
  cat <<EOF
set -euo pipefail

if ${@}; then
  tput bold
  tput setaf 2
  echo -e '\n✅ SUCCESS ✅'
  tput sgr0
else
  tput bold
  tput setaf 1
  echo -e '\n💩 ERROR 💩'
  tput sgr0
fi
EOF
)

if [ "$1" == "--debug" ]; then
  echo DEBUG MODE
  exec watchexec --only-emit-events --emit-events-to stdio
fi

exec watchexec --quiet --clear --restart --stop-timeout=0s --shell=bash -- "$SCRIPT"
