#!/usr/bin/env bash

set -e

# Set some variables
OP=op
OP_FOLDER=$HOME/.op
OP_CONFIG=$OP_FOLDER/config
OP_SESSION_FILE=$OP_FOLDER/session
SCRIPT_NAME=$(basename $0)
C_RED=$(tput setaf 1)
C_GREEN=$(tput setaf 2)
C_YELLOW=$(tput setaf 3)
C_PINK=$(tput setaf 5)
C_BOLD=$(tput bold)
C_RESET=$(tput sgr0)

usage() {
    cat <<EOF
Usage: $SCRIPT_NAME COMMAND [OPTIONS]
Fetch 1password secrets.

Supported commands are:
  login
  logout
  ssh
  token
  credentials

Examples:

  Login to 1password:
    $ $SCRIPT_NAME login -le <EMAIL> -lk <SECRET_KEY_NOT_YOUR_PASSWORD>

  Add ssh key to ssh-agent:
    $ $SCRIPT_NAME ssh -s

  Fetch token:
    $ $SCRIPT_NAME token

  Fetch token with id:
    $ $SCRIPT_NAME token -i xaori6o43fhmyh4zzc34nkayee

  Fetch a website login:
    $ $SCRIPT_NAME credentials

  Logout from 1password:
    $ $SCRIPT_NAME logout

Options:
  -i,  --id=          Skip searching and provide ID of item
  -s,  --ssh-add      Add to ssh agent (only works with ssh-key)
  -le, --login-email  Email to login with
  -lk, --login-key    Secret key (not your master password)
  -h,  --help         Print usage
EOF
    exit 1
}

sh-log-lines() {
    for a in "$@"; do
        printf "\n  $a" 1>&2
    done
    printf "\n" 1>&2
}

sh-log-info() {
    printf "${C_GREEN}INFO${C_RESET}: $1" 1>&2
    sh-log-lines "${@:2}"
}

sh-log-warn() {
    printf "${C_YELLOW}WARN${C_RESET}: $1" 1>&2
    sh-log-lines "${@:2}"
}

sh-log-error() {
    printf "${C_RED}ERROR${C_RESET}: $1" 1>&2
    sh-log-lines "${@:2}"
    exit 1
}

sh-string-highlight() {
    d=""
    for a in "$@"; do
        printf "${C_BOLD}${C_PINK}$d$a${C_RESET}"
        d=" "
    done
}

op-select-generic() {
    $OP item list --format json "$@" | jq -r '.[] | "\(.id) | \(.title)"' | sort | fzf --header 'Select item!' | awk '{print $1}'
}

op-select-category() {
    op-select-generic --categories $1
}

op-select-tag() {
    op-select-generic --tags $1
}

op-get-field() {
    $OP item get $1 --fields $2 --format json | jq -r '.value'
}

# Check for dependencies
command -v jq &>/dev/null || sh-log-error "Binary jq not found!" "Install jq before using this script!"
command -v fzf &>/dev/null || sh-log-error "Binary fzf not found!" "Install fzf before using this script!"
command -v $OP &>/dev/null || sh-log-error "Binary $OP not found!" "Install $OP before using this script!"

# Set permissions
[ -d "$OP_FOLDER" ] || (mkdir -p $OP_FOLDER; chmod 700 $OP_FOLDER)
[ -f "$OP_CONFIG" ] || (echo "{}" > $OP_CONFIG; chmod 600 $OP_CONFIG)

# Check old login
if [ "$(cat $OP_CONFIG | jq -e -r '.latest_signin // empty')" != "" ]; then
    OLD_LOGIN="true"
else
    echo -n "{}" >$OP_CONFIG
    OLD_LOGIN="false"
fi

# Input arguments
COMMAND=""
SSH_ADD="false"
ID=""
LOGIN_EMAIL=""
LOGIN_KEY=""

# Parse input arguments
while [ "$#" -gt 0 ]; do
    case $1 in
    -h | --help)
        usage
        ;;
    -s | --ssh-add)
        SSH_ADD="true"
        ;;
    -i)
        shift
        ID="$1"
        ;;
    --id=*)
        ID=$(echo $1 | awk '{split($0,r,"="); print r[2]}')
        ;;
    -le)
        shift
        LOGIN_EMAIL="$1"
        ;;
    --login-email=*)
        LOGIN_EMAIL=$(echo $1 | awk '{split($0,r,"="); print r[2]}')
        ;;
    -lk)
        shift
        LOGIN_KEY="$1"
        ;;
    --login-key=*)
        LOGIN_KEY=$(echo $1 | awk '{split($0,r,"="); print r[2]}')
        ;;
    *)
        COMMAND="$1"
        ;;
    esac
    shift
done

# Verify command
case $COMMAND in
ssh | token | credentials | login | logout) ;;
*)
    [ "$COMMAND" == "" ] && sh-log-error "No command provided!"
    sh-log-error "Unsupported command: $COMMAND"
    ;;
esac

# Handle login
if [ "$COMMAND" == "login" ]; then
    if [ "$OLD_LOGIN" == "false" ]; then
        ([ "$LOGIN_EMAIL" == "" ] || [ "$LOGIN_KEY" == "" ]) && sh-log-error "First time login!" "Get your secret key here: https://enonic.1password.eu/profile" "Log in by running: $(sh-string-highlight "$SCRIPT_NAME login -le <EMAIL> -lk <SECRET_KEY_NOT_YOUR_PASSWORD>")"
        $OP signin enonic.1password.eu $LOGIN_EMAIL $LOGIN_KEY --raw >$OP_SESSION_FILE
    else
        $OP signin --raw >$OP_SESSION_FILE
    fi
    chmod 600 $OP_SESSION_FILE
    exit 0
fi

# Handle logout
if [ "$COMMAND" == "logout" ]; then
    $OP signout --forget
    rm -f $OP_SESSION_FILE
    exit 0
fi

# Set session
export OP_SESSION_enonic="$(cat $OP_SESSION_FILE 2>/dev/null)"

# Test if session is valid
if [ "$OLD_LOGIN" == "false" ]; then
    $OP vault list >/dev/null 2>&1 || sh-log-error "Not logged in to 1Password!" "Log in by running: $(sh-string-highlight "$SCRIPT_NAME login")"
elif [ "$OP_SESSION_enonic" == "" ]; then
    # Call your self to log in
    sh-log-info "Provide 1password credentials!"
    $SCRIPT_NAME login
    export OP_SESSION_enonic="$(cat $OP_SESSION_FILE 2>/dev/null)"
fi

if $OP vault list 2>&1 | grep "You are not currently signed in" > /dev/null; then
    # Call your self to log in
    sh-log-info "Provide 1password credentials!"
    $SCRIPT_NAME login
    export OP_SESSION_enonic="$(cat $OP_SESSION_FILE 2>/dev/null)"
fi

# Get ID
if [ "$ID" == "" ]; then
    case $COMMAND in
    ssh)
        ID=$(op-select-tag ssh-key)
        ;;
    token)
        ID=$(op-select-category Password)
        ;;
    credentials)
        ID=$(op-select-category Login)
        ;;
    *)
        sh-log-error "Unexpected state!"
        ;;
    esac
fi

# Verify ID is selected
[ "$ID" == "" ] && sh-log-error "No item selected!"

# Fetch fields
case $COMMAND in
ssh)
    if [ "$SSH_ADD" == "true" ]; then
        op-get-field $ID notesPlain | ssh-add -
    else
        op-get-field $ID notesPlain
    fi
    ;;
token)
    op-get-field $ID password
    ;;
credentials)
    echo "$(op-get-field $ID username) $(op-get-field $ID password)"
    ;;
*)
    sh-log-error "Unexpected state!"
    ;;
esac
