#!/usr/bin/env bash

# Manage displays

set -e

SCREENS=($(xrandr --current | sed 's/^\(.*\) connected.*$/\1/p;d'))
BRIGHTNESS=($(xrandr --verbose | grep 'Brightness' | awk '{print $2}'))

TARGET=$1
CMD=$2
CURRENT_BRIGHTNESS=""

i=0
for s in ${SCREENS[@]}; do
    if [ "$TARGET" == "$s" ]; then
        CURRENT_BRIGHTNESS=${BRIGHTNESS[i]}
        CURRENT_BRIGHTNESS=$(awk "BEGIN {print $CURRENT_BRIGHTNESS}")
    fi
    i=$((i + 1))
done

if [ "$CURRENT_BRIGHTNESS" == "" ]; then
    exit 1
fi

case $CMD in
down)
    CURRENT_BRIGHTNESS=$(awk "BEGIN {print ($CURRENT_BRIGHTNESS - 0.1)}")
    ;;
up)
    CURRENT_BRIGHTNESS=$(awk "BEGIN {print ($CURRENT_BRIGHTNESS + 0.1)}")
    ;;
*) ;;
esac

[ $(echo "$CURRENT_BRIGHTNESS>1"| bc) -eq 0 ] || exit 0
[ $(echo "$CURRENT_BRIGHTNESS<0.1"| bc) -eq 0 ] || exit 0

xrandr --output $TARGET --brightness $CURRENT_BRIGHTNESS