#!/usr/bin/env bash

set -euo pipefail

org="kolonialno"
base_repo_dir="$HOME/repos/oda"
shell_to_open_after_checkout="$SHELL" # Disable by setting it to ""

# Prints the unix epoch from $1 days ago
days-ago() {
  local max_days=$1
  local now=$(date +%s)
  echo $(( $now - (86400 * $max_days) ))
}

# Wrapper for the gh command to easily pass in repo $1
gh-pr() {
  gh pr -R ${org}/$1 "${@:2}"
}

# Fetches all PRs from $org based on filters $@
pr-fetch() {
  # Note:
  #   We pass in "phony" repo, but get all PRs?! That's because we are not filtering
  #   PRs by repo, so the "phony" repo does not even have to exist.
  gh-pr phony list --json url,title,createdAt,author -S "org:${org} $(echo $@)"
}

# Views PR $2 from repo $1. You can specify more params to pass to the GH client
pr-view() {
  local repo=$1
  local id=$2

  gh-pr $repo view $id "${@:3}"
}

# Checks out PR $2 from repo $1 locally
pr-checkout() {
  local repo=$1
  local id=$2
  local repo_dir="$base_repo_dir/$repo"

  # Clone repo if needed
  [ -d "$repo_dir" ] || gh repo clone $org/$repo $repo_dir

  # Checkout PR
  cd $repo_dir
  gh pr checkout $pr_id
  echo "🎉 PR checked out here: $repo_dir"
}

# Fetch PRs, group, sort, filter and format for FZF
pr_list=`
{ 
  pr-fetch 'user-review-requested:@me' &
  pr-fetch 'team-review-requested:kolonialno/reliability' 'team-review-requested:kolonialno/infrastructure-developer-experience' &
  wait
} | jq -r -s \ '
  add
  | group_by(.title) | map(.[-1])
  | map(.author.type = (
    if (.author.login | contains("renovate")) 
    or (.author.login | contains("dependabot"))
    then "🧰"
    else "🧑"
    end))
  | sort_by(.createdAt)
  | sort_by(.author.type)
  | .[]
  | select(.createdAt | fromdateiso8601 > '$(days-ago 90)')
  | .author.type + " " + (.url | split("/") | .[-3]) + " #" + (.url | split("/") | .[-1]) + " " + .title
'
`

while true; do
  # Prompt user for PRs
  pr=$(echo "$pr_list" | fzf)
  # pr=$(echo "$pr_list" | tail -n 1)

  # Bail if no PR is selected
  [ -z "$pr" ] && return

  # Extract pr_repo and id
  pr_repo=$(echo $pr | awk '{print $2}')
  pr_id=$(echo $pr | awk '{print $3}')

  # View PR in terminal
  clear
  pr-view $pr_repo $pr_id

  while true; do
    # Ask for command
    read -p "🤔 What to do? [Xcv?]: " -n 1 -r
    case $REPLY in
      "?") # Help
        echo && echo "🛟 Help!"
        echo "  x => 🛑 Close PR"
        echo "  c => 📖 Checkout PR"
        echo "  v => 🌐 View PR in browser"
        echo "  ? => 🛟 Show this help"
      ;;
      "c" | "C") # Checkout
        echo && echo "📖 Checking out PR!"

        # Checkout PR
        pr-checkout $pr_repo $pr_id

        if [ ! -z "$shell_to_open_after_checkout" ]; then
          # Open bash where the PR is
          echo "🐚 Opening PR in shell!"
          exec $shell_to_open_after_checkout
        fi
      ;;
      "v" | "V") # View
        echo && echo "🌐 View PR in browser!"
        pr-view $pr_repo $pr_id --web > /dev/null 2>&1
      ;;
      "x" | "X" | *) # Close
        break
      ;;
    esac
  done
done
