#!/bin/bash

# Script to log in to some services using last pass

set -e

## Docker
docker-login() {
    echo "Using docker credentials $1"
    lpass show --sync=no $1 --password | docker login --username $(lpass show --sync=no $1 --username) --password-stdin
}

## SSH keys
CURRENT_KEY=~/.ssh/id_rsa_lp
ssh-key() {
    ssh-add -D
    echo "Using key $1"
    rm -f $CURRENT_KEY
    lpass show --sync=no $1 --field='Private Key' > $CURRENT_KEY
    chmod 400 $CURRENT_KEY
    SSH_ASKPASS=glogin-ssh-give-pass ssh-add $CURRENT_KEY <<< "$(lpass show --sync=no $1 --field=Passphrase)"
}

"$@"