#!/usr/bin/env bash

set -euo pipefail

SCRIPT_NAME=$(basename $0)

usage() {
    cat 1>&2 <<EOF
Usage: $SCRIPT_NAME HOST

Examples:
  $ $SCRIPT_NAME google.com

EOF
    (log-error "")
    echo -n "  " 1>&2
}

log-lines() { for a in "$@"; do printf "\n  $a" 1>&2 ;done ;printf "\n" 1>&2 ;}
log-error() { printf "$(tput setaf 1)ERROR$(tput sgr0): $1" 1>&2; log-lines "${@:2}"; exit 1; }

HOST=${1:?"HOST <- missing parameter $(usage)"}

size=1272 # Must be divisible by 4
while ping -s $size -M do -c1 $1 >/dev/null 2>&1; do
    ((size += 4))
done

echo "Max MTU size: $((size - 4 + 28))"
