#!/bin/sh

MON1=${1:-$(xrandr | grep " connected" | awk '{print $1}' | head -n 1)}
MON2=${2:-$(xrandr | grep " connected" | awk '{print $1}' | tail -n 1)}

if [ -z "$MON1" ]; then
    echo "Monitor 1: empty, exiting..."
    exit 1
fi

echo "Monitor 1: $MON1 1920x1080"
xrandr --output $MON1 --mode 1920x1080

if [ -z "$MON2" ]; then
    echo "Monitor 2: Skipping"
else
    echo "Monitor 2: $MON2 1920x1080 - right of $MON1"
    xrandr --output $MON2 --mode 1920x1080 --right-of $MON1
fi

echo "Restoring wallpapers"
nitrogen --restore