#!/bin/bash

# Manage displays

set -e

INT=`xrandr --current | sed 's/^\(.*\) connected.*$/\1/p;d' | grep -v ^DP | head -n 1`
EXT=`xrandr --current | sed 's/^\(.*\) connected.*$/\1/p;d' | grep -v ^eDP | head -n 1`

if [[ -z "$EXT" ]]; then
    # No secondary screen
    xrandr --output "${INT}" --auto
else
    xrandr --output "${INT}" --auto --scale 1x1 --output "${EXT}" --auto --scale 1.4x1.4 --pos 0x0 --right-of "${INT}"
fi

sleep 2
nitrogen --restore