#!/usr/bin/env bash

set -euo pipefail

SCRIPT_NAME=$(basename $0)

usage() {
  cat 1>&2 <<EOF
Usage: $SCRIPT_NAME [MODE]

Examples:
  $ $SCRIPT_NAME

EOF
  (log-error "")
  echo -n "  " 1>&2
}

log-lines() {
  for a in "$@"; do printf "\n  $a" 1>&2; done
  printf "\n" 1>&2
}
log-error() {
  printf "$(tput setaf 1)ERROR$(tput sgr0): $1" 1>&2
  log-lines "${@:2}"
  exit 1
}

fetch_rss() {
  curl -s $1 |
    yq -p xml -o json '.rss.channel.item' |
    # Remove image tags
    sed -e "s%<img.*>\\\\n%%g" |
    # Format as quote
    jq -c '.[] | {text: .description, attribution: .link}'
}

fetch_rss_more() {
  curl -s $1 |
    yq -p xml -o json '.rss.channel.item' |
    # Remove image tags
    sed -e "s%<img.*>\\\\n%%g" |
    # Format as quote
    jq -c '.[] | {text: (.title + ". " + .description), attribution: .link}'
}

fetch_code() {
  OLDIFS="$IFS"
  IFS=$'\n'
  for in in $(rg --max-depth 5 -m 1 $1 -g $2 ~/repos/personal/ |
    rg ':' |
    sed 's/:/%%/' |
    shuf |
    head -n 20); do

    jq -c --null-input --arg in "$in" '$in | split("%%") | {"attribution":.[0], text: .[1]}'
  done
  IFS="$OLDIFS"
}

mode_news() {
  fetch_rss https://www.mbl.is/feeds/innlent/ &
  fetch_rss https://www.mbl.is/feeds/erlent/ &
  fetch_rss https://www.mbl.is/feeds/togt/ &
  fetch_rss https://www.mbl.is/feeds/helst/ &
  fetch_rss https://www.visir.is/rss/forsida/ &
  fetch_rss_more http://feeds.bbci.co.uk/news/technology/rss.xml
}

mode_quotes() {
  curl -s http://api.quotable.io/quotes/random?limit=100 |
    # Format as quote
    jq -c '.[] | {text: .content, attribution: .author}'
}

mode_text() {
  mode_quotes &
  mode_news
}

mode_program() {
  fetch_code '^fn' '*.{rs}' &
  fetch_code '^def' '*.{py}'
}

mode_mix() {
  mode_program &
  mode_text
}

MODE=${1:-text}

mode_${MODE} |
  awk 'length>80' |
  awk 'length<250' |
  # Remove characters I never use
  sed 's/„/\\"/g' |
  sed 's/“/\\"/g' |
  # grep "Fataverslun" |
  sed 's/&amp;/\&/g' |
  # Remove duplicates and randomize
  sort |
  uniq |
  jq -s '.' |
  tt -noreport -quotes - -csv >~/.${SCRIPT_NAME}-${MODE}.csv
