#!/usr/bin/env bash

set -euo pipefail

REC=$(mktemp -u rec-XXX)

if [[ $# -eq 0 ]]; then
    set -- "fish -C 'set fish_autosuggestion_enabled 0'"
fi

asciinema rec -c "$@" /tmp/${REC}
agg /tmp/${REC} ${REC}.gif --cols 80 --rows 30
