#!/usr/bin/env python

# For use in vim with !snipd to format snipd exports to my liking!

import sys

lines = []
last_line = ""

for line in sys.stdin:
    if line == "\n" and line == last_line:
        continue

    if (
        line.startswith("- Tags")
        or line.startswith("- Export date")
        or line.startswith("Created with")
        or line.startswith("### ✨ Summary")
        or line.startswith("#### 📚 Transcript")
        or line.startswith("![Cover|200]")
    ):
        continue

    if (last_line.startswith("##") and line != "\n") or (
        line.startswith("<details>") and last_line != "\n"
    ):
        lines.append("\n")

    spons = line.find("Sponsors:")
    if spons > 0:
        line = line[:spons] + "\n"

    if last_line.startswith("[🎧 Play snip"):
        lines.append("\n")

    line = line.replace("Owner / Host::", "Host::")
    line = line.replace("> <", "><")
    line = line.replace(
        "<summary>Click to expand</summary>", "<summary>Show transcript</summary>"
    )
    line = line.replace(":: ", ": ")
    line = line.replace("<br/>>  ", " ")
    line = line.replace("<br/><br/>", "<br/><br/>\n")
    line = line.replace("</blockquote>", "\n</blockquote>")

    line = line.replace(
        "</blockquote><br/><blockquote>", "</blockquote>\n<br/>\n<blockquote>"
    )

    last_line = line
    lines.append(line)

line_length = 98
for line in lines:
    # while len(line) > line_length:
    #     idx = line.rfind(" ", 0, line_length)
    #
    #     if idx == -1:
    #         break
    #
    #     print(line[:idx], end="")
    #     line = line[idx:]
    #     sys.exit(1)

    print(line.strip())
