---
- hosts: localhost

  # https://github.com/JaKooLit/Debian-Hyprland/blob/main/install-scripts/hyprland-qtutils.sh

  vars:
    # renovate: datasource=github-tags depName=hyprland-qtutils packageName=hyprwm/hyprland-qtutils
    version: v0.1.5
    dir: "/tmp/hyprwm-hyprland-qtutils"

  tasks:
    - name: Install hyprland-qtutils dependencies
      become: true
      apt:
        state: latest
        update_cache: true
        pkg:
          - libqt6core5compat6
          - qt6-base-dev
          - qt6-wayland-dev
          - qt6-wayland
          - qt6-declarative-dev
          - qml6-module-qtcore
          - qt6-3d-dev
          - qt6-5compat-dev
          - libqt6waylandclient6
          - qml6-module-qtwayland-client-texturesharing

    - name: Checkout hyprland-qtutils
      ansible.builtin.git:
        repo: https://github.com/hyprwm/hyprland-qtutils.git
        dest: "{{ dir }}"
        recursive: true
        version: "{{ version }}"
        force: true

    - name: Build hyprland-qtutils
      shell:
        chdir: "{{ dir }}"
        cmd: |
          cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
          cmake --build ./build --config Release --target all -j `nproc`

    - name: Install hyprland-qtutils
      become: true
      shell:
        chdir: "{{ dir }}"
        cmd: |
          sudo cmake --install ./build
