---
- hosts: "{{ host }}"

  # https://github.com/JaKooLit/Debian-Hyprland/blob/main/install-scripts/hyprland.sh

  vars:
    # renovate: datasource=github-tags depName=hyprland packageName=hyprwm/Hyprland
    version: v0.54.2
    dir: "/tmp/hyprwm-hyprland"

  tasks:
    - name: Check if skip
      meta: end_play
      when: '"hyprland" in skip'

    - name: Install hyprland dependencies
      become: true
      apt:
        state: latest
        update_cache: true
        pkg:
          - clang
          - llvm
          - libxcb-errors-dev
          - libre2-dev
          - libudis86-dev
          - libinotify-ocaml-dev

    - name: Checkout hyprland
      ansible.builtin.git:
        repo: https://github.com/hyprwm/Hyprland.git
        dest: "{{ dir }}"
        recursive: true
        version: "{{ version }}"
        force: true

    # We can potentially drop this when GCC15 is available on debian
    - name: Create a file with specific content
      ansible.builtin.copy:
        src: 0001-fix-hyprland-compile-issue.patch
        dest: "{{ dir }}/0001-fix-hyprland-compile-issue.patch"

    - name: Build hyprland
      shell:
        chdir: "{{ dir }}"
        cmd: |
          patch -p1 < 0001-fix-hyprland-compile-issue.patch
          PKG_CONFIG_PATH=/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/share/pkgconfig:$PKG_CONFIG_PATH CXX=clang++ CXXFLAGS=-std=gnu++26 make all

    - name: Install hyprland
      become: true
      shell:
        chdir: "{{ dir }}"
        cmd: |
          sudo make install
