#!/bin/bash

set -e

# Colors
WARN='\033[93m'
FAIL='\033[91m'
ENDC='\033[0m'
BOLD='\033[1m'
OKBL='\033[94m'
OKGR='\033[92m'

echoerr() { echo $@ 1>&2; }

# Check if we are doing bash completion
if [[ $@ == *"kubectl completion bash"* ]]; then
	exec "$@"
	exit 0
fi

# Check if we are doing kube config
if [[ $@ == *"kubectl config"* ]]; then
	exec "$@"
	exit 0
fi

# Check our current context
CTX=$(kubectl config current-context)
if [[ ${CTX} = *"-dev_"* ]] || [[ ${CTX} = "minikube" ]] || [[ ${CTX} = *"monifairapi"* ]] || [[ ${CTX} = *"-test-"* ]]; then
    DEV_ENV=1
else
    DEV_ENV=0
fi

BLOCK=${KUBE_CTX_BLOCK:-1}

if [[ ${DEV_ENV} -eq "0" ]] && [[ ${BLOCK} -ne "0" ]]; then
    echoerr -e -n "${FAIL}${BOLD}Command failed!${ENDC} "
    echoerr -e "You are trying to issue command '${OKGR}$@${ENDC}' on a live cluster. Current context is '${OKBL}${CTX}${ENDC}'. To disable this check, run:"
    echoerr -e " * ${WARN}KUBE_CTX_BLOCK=0 $@${ENDC} (disable for this one command)"
    echoerr -e " * ${WARN}export KUBE_CTX_BLOCK=0${ENDC} (disable for this terminal session)"
    exit -1
elif [[ ${DEV_ENV} -eq "0" ]]; then
    echoerr -e -n "${WARN}Warning!${ENDC} "
fi

echoerr -e "Issuing command '${OKGR}$@${ENDC}' on cluster '${OKBL}${CTX}${ENDC}'."
echoerr ""

exec "$@"