---
- hosts: localhost
  gather_facts: true

  tasks:
    - name: Add fish repo
      become: true
      apt_repository:
        repo: 'ppa:fish-shell/release-3'
        state: present

    - name: Install fish
      become: true
      apt:
        state: latest
        update_cache: true
        pkg: fish
