---
- hosts: localhost
  tasks:

    - name: Ensure fonts directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory

    - name: JetBrainsMono exists
      shell: "ls {{ lookup('env', 'HOME') }}/.fonts/JetBrainsMonoNerdFont*"
      register: jbm_exists
      changed_when: false
      ignore_errors: true

    - name: Download JetBrainsMono
      when: jbm_exists is failed
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/JetBrainsMono.zip
        dest: "{{ lookup('env', 'HOME') }}/.fonts/"
        remote_src: true
