---
- hosts: localhost
  gather_facts: true

  tasks:
    - name: Check if fish is installed
      command: which fish
      changed_when: false
      failed_when: fish_installed.rc not in [0,1]
      register: fish_installed

    - name: Add fish shell PPA GPG key
      when: fish_installed.rc not in [ 0 ]
      become: true
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 88421E703EDC7AF54967DED473C9FCC9E2BB48DA
        keyring: /usr/share/keyrings/fish.gpg
        state: present

    - name: Add fish repo
      when: fish_installed.rc not in [ 0 ]
      become: true
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/fish.gpg] https://ppa.launchpadcontent.net/fish-shell/release-4/ubuntu {{ ansible_distribution_release }} main"
        state: present
        filename: fish

    - name: Install fish
      become: true
      apt:
        state: latest
        update_cache: true
        pkg: fish
