---
- hosts: localhost
  tasks:

    - name: Install cargo package
      community.general.cargo:
        name: "{{ item }}"
        state: latest
      with_items:
        - lsd  # Better ls
        - drill  # HTTP stress testing
        - xh  # HTTPie clone
        - starship  # Fancy prompt
        - ouch  # Easy compress/decompress
        - sfz  # Simple web server for dirs
        - alacritty  # Better terminal emulator
        - trunk  # WASM development
        - cargo-tarpaulin  # For code coverage
        - git-delta  # Better diff
        - watchexec-cli  # Used for 'dev' script
        - oha  # http stress tests
        - mise  # asdf clone
