---
- hosts: localhost
  tasks:
    - name: Check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: true

    - name: Download Installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'

    - name: Install rust/cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y

    - name: Source cargo env
      lineinfile:
        path: "{{ item.path }}"
        line: "{{ item.line }}"
      with_items:
        - path: ~/.bashrc
          line: "[ -f ~/.cargo/env ] && source $HOME/.cargo/env"
