---
- hosts: localhost
  tasks:

    - name: Install packages
      become: true
      apt:
        state: latest
        update_cache: true
        pkg:
          # Bare essentials
          - apt-transport-https
          - build-essential
          - cmake
          - direnv
          - git

          # Python dependencies
          - libbz2-dev
          - libffi-dev
          - liblzma-dev
          - libncurses-dev
          - libreadline6-dev
          - libsqlite3-dev
          - libssl-dev
          - tk-dev

          # Py-Spy dependencies
          - libunwind-dev

          # Other
          - flameshot     # For screenshots
          - fzf           # Fuzzy finder
          - gnome-tweaks  # Tweak gnome
          - jq            # Json manipulation
          - tmux          # Terminal good stuff
          - tree          # Tree for directories
          - wireguard     # VPN
          - xclip         # For nvim clipboard
