---
- hosts: localhost
  gather_facts: true

  vars:
    # renovate: datasource=github-releases depName=regolith-desktop packageName=regolith-linux/regolith-desktop
    version: v3.2

  tasks:
    - name: Set DPKG architecture
      set_fact:
        dpkg_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

    - name: Add Regolith GPG apt Key
      become: true
      apt_key:
        url: https://archive.regolith-desktop.com/regolith.key
        state: present

    - name: Add Regolith Apt Repository
      become: true
      apt_repository:
        repo: "deb [arch={{ dpkg_arch }}] https://archive.regolith-desktop.com/ubuntu/stable noble {{ version }}"

    - name: Install Regolith
      become: true
      apt:
        state: latest
        update_cache: true
        pkg:
          - regolith-desktop
          - regolith-compositor-picom-glx
          - regolith-session-flashback
          - regolith-look-lascaille
          - regolith-look-nord
          - i3xrocks-battery
          - i3xrocks-cpu-usage
          - i3xrocks-keyboard-layout
          - i3xrocks-memory
          - i3xrocks-time
          - dunst  # Notification popups

    - name: Remove unwanted packages
      become: true
      apt:
        state: absent
        pkg:
          - i3xrocks-net-traffic
          - i3xrocks-bluetooth
          - regolith-rofication  # Default notification system
