---
- hosts: localhost
  tasks:

  - name: Create local bin path
    ansible.builtin.file:
      path: ~/.local/bin
      state: directory

  - name: Check if gh is installed
    command: which gh
    changed_when: false
    failed_when: gh_installed.rc not in [0,1]
    register: gh_installed

  - name: Install gh
    when: gh_installed.rc not in [ 0 ]
    unarchive:
      remote_src: yes
      src: https://github.com/cli/cli/releases/download/v2.32.1/gh_2.32.1_linux_amd64.tar.gz
      dest: ~/.local/bin
      extra_opts:
      - --strip-components
      - 2
      # - --add-file
      - gh_2.32.1_linux_amd64/bin/gh

  - name: Check if lazygit is installed
    command: which lazygit
    changed_when: false
    failed_when: lazygit_installed.rc not in [0,1]
    register: lazygit_installed

  - name: Install lazygit
    when: lazygit_installed.rc not in [ 0 ]
    unarchive:
      remote_src: yes
      src: https://github.com/jesseduffield/lazygit/releases/download/v0.38.2/lazygit_0.38.2_Linux_x86_64.tar.gz
      dest: ~/.local/bin
      extra_opts:
      - lazygit

  - name: Check if nvim is installed
    command: which nvim
    changed_when: false
    failed_when: nvim_installed.rc not in [0,1]
    register: nvim_installed

  - name: Install nvim
    when: nvim_installed.rc not in [ 0 ]
    unarchive:
      remote_src: yes
      src: https://github.com/neovim/neovim/releases/download/v0.9.1/nvim-linux64.tar.gz
      dest: ~/.local/bin

  - name: Link nvim
    when: nvim_installed.rc not in [ 0 ]
    ansible.builtin.file:
      src: ~/.local/bin/nvim-linux64/bin/nvim
      dest: ~/.local/bin/nvim
      state: link
