---
- hosts: localhost
  tasks:

  - name: Install cargo package
    community.general.cargo:
      name: "{{ item }}"
      state: latest
    with_items:
    - drill           # HTTP stress testing
    - xh              # HTTPie clone
    - starship        # Fancy prompt
    - ouch            # Easy compress/decompress
    - sfz             # Simple web server for dirs
