---
- hosts: localhost
  gather_facts: true
  tasks:

  - name: Set DPKG architecture
    set_fact:
      dpkg_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

  - name: Add 1password GPG apt Key
    become: true
    apt_key:
      url: https://downloads.1password.com/linux/keys/1password.asc
      state: present

  - name: Add 1password Apt Repository
    become: true
    apt_repository:
      repo: "deb https://downloads.1password.com/linux/debian/{{ dpkg_arch }} stable main"
      state: present

  - name: Install 1password
    become: true
    apt:
      state: latest
      update_cache: true
      pkg:
      - 1password
      - 1password-cli
