---
- hosts: localhost
  tasks:

  - name: Check if lazygit is installed
    command: which lazygit
    changed_when: false
    failed_when: lazygit_installed.rc not in [0,1]
    register: lazygit_installed

  - name: Install lazygit
    when: lazygit_installed.rc not in [ 0 ]
    unarchive:
      remote_src: yes
      src: https://github.com/jesseduffield/lazygit/releases/download/v0.38.2/lazygit_0.38.2_Linux_x86_64.tar.gz
      dest: ~/.local/bin
      extra_opts:
      - lazygit
