---
- hosts: localhost
  tasks:

  - name: Set asdf dir
    set_fact:
      asdf_dir: "{{ dotfiles }}/.asdf"
      asdf_bin: "{{ dotfiles }}/.asdf/bin/asdf"

  - name: Git checkout asdf
    git:
      repo: https://github.com/asdf-vm/asdf.git
      dest: "{{ asdf_dir }}"
      version: v0.11.3

  - name: Source asdf
    lineinfile:
      path: "{{ item.path }}"
      line: "{{ item.line }}"
    with_items:
    - path: ~/.bashrc
      line: "source {{ asdf_dir }}/asdf.sh"
    - path: ~/.bashrc
      line: "source {{ asdf_dir }}/completions/asdf.bash"
    - path: ~/.profile
      line: 'PATH="{{ asdf_dir }}/shims:$PATH"'

  - name: Get plugins
    shell: "cat {{ dotfiles }}/.tool-versions | awk '{ print $1}'"
    register: plugins

  - name: Add missing asdf plugins
    shell: "{{ asdf_bin }} plugin-list | grep {{ item }} || {{ asdf_bin }} plugin-add {{ item }}"
    with_items: "{{ plugins.stdout.split('\n') }}"

  - name: Install tools
    shell: "{{ asdf_bin }} install"
