---
- hosts: localhost

  vars:
    # renovate: datasource=github-releases depName=velero packageName=vmware-tanzu/velero
    version: v1.16.1

  tasks:
    - name: Create local bin path
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory

    - name: Check if velero is installed
      shell: "velero version --client-only | grep {{ version }}"
      changed_when: false
      failed_when: velero_installed.rc not in [0,1]
      register: velero_installed

    - name: Install velero
      when: velero_installed.rc not in [ 0 ]
      unarchive:
        remote_src: yes
        src: "https://github.com/vmware-tanzu/velero/releases/download/{{ version }}/velero-{{ version }}-linux-amd64.tar.gz"
        dest: ~/.local/bin
        extra_opts:
          - --strip-components
          - 1
          # - --add-file
          - "velero-{{ version }}-linux-amd64/velero"
