---
- hosts: localhost

  vars:
    # renovate: datasource=github-releases depName=k9s packageName=derailed/k9s
    version: v0.50.11

  tasks:
    - name: Create local bin path
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory

    - name: Check if k9s is installed
      shell: "k9s version | grep {{ version }}"
      changed_when: false
      failed_when: k9s_installed.rc not in [0,1]
      register: k9s_installed

    - name: Install k9s
      when: k9s_installed.rc not in [ 0 ]
      unarchive:
        remote_src: yes
        src: https://github.com/derailed/k9s/releases/download/{{ version }}/k9s_Linux_amd64.tar.gz
        dest: ~/.local/bin
        extra_opts:
          - k9s
