---
- hosts: localhost

  vars:
    # renovate: datasource=github-releases depName=cli packageName=cli/cli
    version: v2.43.1

  tasks:

    - name: Create local bin path
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory

    - name: Check if gh is installed
      shell: "gh --version | grep {{ version }}"
      changed_when: false
      failed_when: gh_installed.rc not in [0,1]
      register: gh_installed

    - name: Install gh
      when: gh_installed.rc not in [ 0 ]
      unarchive:
        remote_src: yes
        src: "https://github.com/cli/cli/releases/download/{{ version }}/gh_{{ version[1:] }}_linux_amd64.tar.gz"
        dest: ~/.local/bin
        extra_opts:
          - --strip-components
          - 2
          # - --add-file
          - "gh_{{ version[1:] }}_linux_amd64/bin/gh"
