---
- hosts: localhost

  vars:
    # renovate: datasource=github-releases depName=ollama packageName=ollama/ollama
    version: 0.4.0

  tasks:
    - name: Create local bin path
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory

    - name: Check if ollama is installed
      shell: "ollama --version | grep {{ version }}"
      changed_when: false
      failed_when: ollama_installed.rc not in [0,1]
      register: ollama_installed

    - name: Install ollama
      when: ollama_installed.rc not in [ 0 ]
      become: true
      shell: "curl -fsSL https://ollama.com/install.sh | OLLAMA_VERSION={{ version }} sh"
      register: install
      notify:
        - restart_ollama

    - name: Print out
      when: ollama_installed.rc not in [ 0 ]
      debug: var=install.stdout_lines

  handlers:
    - name: restart_ollama
      become: true
      failed_when: false
      ansible.builtin.systemd:
        name: ollama
        state: restarted
        enabled: true
