---
- hosts: localhost

  vars:
    version: 1.31.2

  tasks:

  - name: Create local bin path
    ansible.builtin.file:
      path: ~/.local/bin
      state: directory

  - name: Check if minikube is installed
    shell: "minikube version | grep {{ version }}"
    changed_when: false
    failed_when: minikube_installed.rc not in [0,1]
    register: minikube_installed

  - name: Install minikube
    when: minikube_installed.rc not in [ 0 ]
    ansible.builtin.get_url:
      url: https://github.com/kubernetes/minikube/releases/download/v{{ version }}/minikube-linux-amd64
      dest: ~/.local/bin/minikube

  - name: Set minikube permissions
    when: minikube_installed.rc not in [ 0 ]
    ansible.builtin.file:
      path: ~/.local/bin/minikube
      state: touch
      mode: +x
