---
- hosts: localhost

  vars:
    # renovate: datasource=github-releases depName=kubectx packageName=ahmetb/kubectx
    version: v0.9.5

  tasks:

    - name: Create local bin path
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory

    - name: Check if kubectx is installed
      shell: "kubectl-ctx --version | grep {{ version[1:] }}"
      changed_when: false
      failed_when: kc_installed.rc not in [0,1]
      register: kc_installed

    - name: Install kubectx
      when: kc_installed.rc not in [ 0 ]
      unarchive:
        remote_src: yes
        src: "https://github.com/ahmetb/kubectx/releases/download/{{ version }}/kubectx_{{ version }}_linux_x86_64.tar.gz"
        dest: ~/.local/bin
        extra_opts:
          - "kubectx"

    - name: Rename bin
      when: kc_installed.rc not in [ 0 ]
      command: "ln -sf ~/.local/bin/kubectx ~/.local/bin/kubectl-ctx"
